PREFIX :<http://www.semanticweb.org/group18/movie-ontology#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd:<http://www.wikidata.org/entity/>
PREFIX wdp:<http://www.wikidata.org/prop/direct/>
PREFIX emotion:<http://www.semanticweb.org/group18/movie-ontology#Emotion/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?name (((COUNT(DISTINCT ?c1)) / (COUNT(DISTINCT ?c2))) AS ?ratio)
    WHERE {
    	?c1 rdf:type :Comment .
        ?c1 :refersToMovie ?movie .
    	?c1 :hasEmotion emotion:Positive .
    	?c2 rdf:type :Comment .
    	?c2 :refersToMovie ?movie .

        { SERVICE <https://query.wikidata.org/sparql> {
            ?movie wdp:P1476 ?name .
        }}
} GROUP BY ?name
ORDER BY DESC(?ratio)
LIMIT 3